version: "3"

services:
  pool.service:
    container_name: pool.service
    ports:
      - 1313:80
    restart: always
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
  pool.php:
    container_name: pool.service.php
    restart: always
    build:
      context: .
      dockerfile: docker/php/Dockerfile
  pool.mysql:
    container_name: "pool.service.mysql"
    restart: "always"
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
